handlers=java.util.logging.ConsoleHandler
.level=INFO
org.bouncycastle.level=FINEST
java.util.logging.ConsoleHandler.level=FINEST
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=%4$s %3$s: %5$s%n
